# analysis_options.yaml

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Verlangt, dass öffentliche Mitglieder wie Klassen und Properties im Pascal Case sind
    public_member_api_docs: true
    
    # Verlangt, dass Rückgabewerte in Methoden immer spezifiziert werden
    always_declare_return_types: true
    
    # Verlangt, dass alle Rückgabewerte in Methoden immer einen Typ haben
    always_specify_types: true
    
    # Verlangt, dass Konstruktoren immer zuerst in der Klasse erscheinen
    sort_constructors_first: true
    
    # Bevorzugt die Verwendung von final für Felder
    prefer_final_fields: true

    # Verhindert Methoden, die länger als 80 Zeichen pro Zeile sind
    lines_longer_than_80_chars: true
    
    # Verhindert die Verwendung von print im Produktionscode
    avoid_print: true
    
    # Verlangt, dass einfache Anführungszeichen verwendet werden
    prefer_single_quotes: true
